let states=JSON.parse(localStorage.getItem("del-word-states")||"{}"),saved=JSON.parse(localStorage.getItem("del-saved")||"{}"),savedArticles=JSON.parse(localStorage.getItem("del-saved-articles")||"{}"),currentType="all",currentSpeakingType="all",currentArticle=null;
function show(id){document.querySelectorAll("main>section").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.id===id));scrollTo(0,0)}
function renderArticles(){let q=(articleSearch.value||"").toLowerCase();articleList.innerHTML=articles.filter(a=>JSON.stringify(a).toLowerCase().includes(q)).slice().reverse().map(a=>`<div class="card" onclick="openArticle(${a.n})"><div class="meta">#${a.n} · ${a.cat} · ${a.framework}</div><h3>${a.title}</h3><p class="idea">${a.idea}</p></div>`).join("")}
function setType(t,b){currentType=t;b.parentElement.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderWords()}
function label(t){return t==="academic"?"Academic / Technical":t==="proper"?"Proper Noun":"Vocabulary"}
function cycle(w){let order=["new","fuzzy","known"],v=states[w]||"new";states[w]=order[(order.indexOf(v)+1)%3];localStorage.setItem("del-word-states",JSON.stringify(states));renderWords()}
function stateText(w){return states[w]==="known"?"✓ 认识":states[w]==="fuzzy"?"~ 模糊":"? 不认识"}
function toggleSave(w){saved[w]=!saved[w];localStorage.setItem("del-saved",JSON.stringify(saved));renderWords()}
function renderWords(){let q=(wordSearch.value||"").toLowerCase();wordList.innerHTML=words.filter(x=>(currentType==="all"||x.type===currentType||(currentType==="saved"&&saved[x.w]))&&(x.w+x.zh+x.ex).toLowerCase().includes(q)).map(x=>`<div class="card"><div class="type">${label(x.type)} · ${x.src}</div><div class="wordline"><div><div class="word">${x.w}</div><div class="zh">${x.zh}</div></div><button class="ghost" onclick='toggleSave(${JSON.stringify(x.w)})'>${saved[x.w]?"★":"☆"}</button></div><p class="example">${x.ex}</p><button class="ghost" onclick='cycle(${JSON.stringify(x.w)})'>${stateText(x.w)}</button></div>`).join("")}
function setSpeakingType(t,b){currentSpeakingType=t;b.parentElement.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSpeaking()}
function toggleAnswer(i){document.getElementById("answer-"+i).classList.toggle("hidden");let b=document.getElementById("reveal-"+i);b.textContent=document.getElementById("answer-"+i).classList.contains("hidden")?"Reveal answer ↓":"Hide answer ↑"}
function renderSpeaking(){speakingList.innerHTML=speakingCards.filter(x=>currentSpeakingType==="all"||x.cat===currentSpeakingType).map((x,i)=>`<div class="card speaking-card"><div class="meta">${x.src} · ${x.cat}</div><div class="question">${x.q}</div><div class="framework"><b>Framework:</b> ${x.framework}</div><button id="reveal-${i}" class="ghost reveal" onclick="toggleAnswer(${i})">Reveal answer ↓</button><div id="answer-${i}" class="answer hidden"><div class="eyebrow">Full response</div><p>${x.answer}</p><div class="eyebrow">Reusable expressions</div>${x.expr.map(e=>`<div class="expression">${e}</div>`).join("")}<div class="related">Related article · ${x.src}</div></div></div>`).join("")}
function renderExpr(){exprList.innerHTML=expressions.map(x=>`<div class="card"><div class="meta">${x[1]}</div><h3>${x[0]}</h3></div>`).join("")}
function formatArticleBody(full){if(/<p[\s>]/i.test(full))return full;return full.trim().split(/\n\s*\n/).map(p=>`<p>${p.trim()}</p>`).join("")}
function openArticle(n){let a=articles.find(x=>x.n===n);currentArticle=n;reader.classList.remove("hidden");document.body.style.overflow="hidden";saveArticle.textContent=savedArticles[n]?"★ Saved":"☆ Save";let full=archivedArticles[String(n)];let status=full?`<span class="archiveBadge">✓ Historical English text imported</span>`:(n===1?`<div class="note">#1 的标题和课程标签已经归档，但我们还没有找到它的历史全文，所以暂时不伪造原文。找到后可以直接补进来。</div>`:`<div class="note">这篇文章目前保存的是课程索引和核心观点，历史全文还没有正式搬入。</div>`);readerContent.innerHTML=`<div class="eyebrow" style="margin-top:28px">Daily English Article · #${a.n}</div><h2>${a.title}</h2><span class="pill">${a.cat}</span><span class="pill">${a.framework}</span><p class="idea"><b>Core idea:</b> ${a.idea}</p>${status}<h3 class="sectionTitle">English Article</h3>${full?`<div class="articleBody" style="font-size:16.5px">${formatArticleBody(full)}</div>`:`<p class="placeholder">Full archived text not imported yet.</p>`}${archivedSummaries[String(n)]?`<h3 class="sectionTitle">中文概要</h3><div class="note">${archivedSummaries[String(n)]}</div>`:""}`}
function closeArticle(){reader.classList.add("hidden");document.body.style.overflow="";currentArticle=null}
function toggleArticleSave(){if(!currentArticle)return;savedArticles[currentArticle]=!savedArticles[currentArticle];localStorage.setItem("del-saved-articles",JSON.stringify(savedArticles));saveArticle.textContent=savedArticles[currentArticle]?"★ Saved":"☆ Save"}
function randomReview(){let p=[...articles.map(x=>({t:"#"+x.n+" · "+x.framework,v:x.idea})),...speakingCards.map(x=>({t:x.src+" · Speaking Question",v:x.q}))];let x=p[Math.floor(Math.random()*p.length)];randomTitle.textContent=x.t;randomText.textContent=x.v}
document.getElementById('articleCount').textContent=articles.length;
document.getElementById('wordCount').textContent=words.length;
document.getElementById('speakingCount').textContent=speakingCards.length;
document.getElementById('archiveDescription').textContent=articles.length+' articles · '+Object.keys(archivedArticles).length+' full texts · '+Object.keys(archivedSummaries).length+' Chinese summaries';
renderArticles();renderWords();renderSpeaking();renderExpr();

function setTheme(choice){if(choice==='auto'){document.documentElement.removeAttribute('data-theme');}else{document.documentElement.setAttribute('data-theme',choice);}localStorage.setItem('readingTheme',choice);document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===choice));}
(function(){setTheme(localStorage.getItem('readingTheme')||'auto');})();
